### ISSUE TITLE
セレクトページ〜アニメーション〜リザルトページ遷移

### ISSUE THREAD

**Issue by y129may9th** [flutteruniv/recommender#24]
関連 Issue: #5

## 概要
セレクトページのボタン活性化 | ダイアログ表示
:---: | :---:
<img src="https://user-images.githubusercontent.com/44105111/205941475-4ede80b8-db2f-400f-be71-9054dd4ddfa3.png" width="50%"> | <img src="https://user-images.githubusercontent.com/44105111/205941533-ce7377d6-20ab-4b9f-b046-477f49d51d7c.png" width="50%">

- セレクトページ -> アニメーション -> リザルトページの遷移
- ダイアログの実装

## 詳細
- セレクトページからアニメーション起動するようにする。
- セレクトボタンを押したあとで、ランダムでデータを取ってくるようにする。
- 「絞り込み」側のボタンを押したら、ダイアログを表示する。

## ディレクトリ、ファイル名
lib/pages/select_page.dart

## その他
不明点などは、このIssueにコメントお願いします！

**Comment by kitashio** [comment]
@dongri727 
どんぐりさんChangeNotifierなどでご対応ありがとうございました😭
FirestoreRepositoryなどちょっと使いづらかったので少し修正してます！
先ほどプルリクをだしたので、それがマージされる前提のお話です！

① SelectPageをStatefulWidgetにしたので、initStateメソッドを追加してfetchItemsを呼び出す。
fetchItemsはFutureメソッドなので、[こちらの記事](https://zenn.dev/minami_hiroto/articles/62a7043a73d123)のようにすると良いかも！
setStateで受け取ったデータを既にあるList型のitemsに格納する。

②ランダムボタンを選択してanimationPageへ遷移する時にgetRandomItemで取得したアイテムを渡す。

どんぐりさんしごできだからこんなに説明必要ないかも😥万が一、詰まったらまたいつでも聞いてください！

**Comment by kitashio** [comment]
あとanimationPageからResultPageに遷移する時にさらにアイテムを渡す必要がありますね！

**Comment by kitashio** [comment]
ResultPageでもう一度ボタンを押した時のこと考えてなかった！
animationPageに遷移する時にitemだけじゃなく、itemsも渡すようにするといける？🧐
